### ISSUE TITLE
I don't know what "HA" stands for

### ISSUE THREAD

**Issue by sandro-pasquali** [david-mark/Funhouse#1]
I think it means "Home Automation", but I had to read the intro twice to figure that out.

Maybe write about some problems that this project aims to solve. I may be wrong, but I think automation works best when I don't have to know anything to use it, other than how to push the button marked "[solve some problem]". 

Maybe you want to talk only to technical people. But you have written "Goal is to be able to communicate using natural language..." and "There will be a heavy emphasis on the home monitoring side of automation". I think you will have great success with this if the average person (the growing casual coder/hobbyist market) has a reason to use it.

**Comment by david-mark** [comment]
Good point. Just getting started on this and definitely will spell out Home Automation more prominently in future. Thanks!

As for the intended audience, if you can install software and copy and paste text, this project is for you. If you can write code as well, then all the better.
